/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as JoinEventIdRouteImport } from './routes/join/$eventId'
import { Route as AdminEventsIndexRouteImport } from './routes/admin/events/index'
import { Route as AdminEventsNewRouteImport } from './routes/admin/events/new'
import { Route as AdminEventsEventIdRouteImport } from './routes/admin/events/$eventId'
import { Route as AdminEventsEventIdChecklistRouteImport } from './routes/admin/events/$eventId/checklist'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinEventIdRoute = JoinEventIdRouteImport.update({
  id: '/join/$eventId',
  path: '/join/$eventId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEventsIndexRoute = AdminEventsIndexRouteImport.update({
  id: '/admin/events/',
  path: '/admin/events/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEventsNewRoute = AdminEventsNewRouteImport.update({
  id: '/admin/events/new',
  path: '/admin/events/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEventsEventIdRoute = AdminEventsEventIdRouteImport.update({
  id: '/admin/events/$eventId',
  path: '/admin/events/$eventId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEventsEventIdChecklistRoute =
  AdminEventsEventIdChecklistRouteImport.update({
    id: '/checklist',
    path: '/checklist',
    getParentRoute: () => AdminEventsEventIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/join/$eventId': typeof JoinEventIdRoute
  '/admin/events/$eventId': typeof AdminEventsEventIdRouteWithChildren
  '/admin/events/new': typeof AdminEventsNewRoute
  '/admin/events/': typeof AdminEventsIndexRoute
  '/admin/events/$eventId/checklist': typeof AdminEventsEventIdChecklistRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/join/$eventId': typeof JoinEventIdRoute
  '/admin/events/$eventId': typeof AdminEventsEventIdRouteWithChildren
  '/admin/events/new': typeof AdminEventsNewRoute
  '/admin/events': typeof AdminEventsIndexRoute
  '/admin/events/$eventId/checklist': typeof AdminEventsEventIdChecklistRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/join/$eventId': typeof JoinEventIdRoute
  '/admin/events/$eventId': typeof AdminEventsEventIdRouteWithChildren
  '/admin/events/new': typeof AdminEventsNewRoute
  '/admin/events/': typeof AdminEventsIndexRoute
  '/admin/events/$eventId/checklist': typeof AdminEventsEventIdChecklistRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/join/$eventId'
    | '/admin/events/$eventId'
    | '/admin/events/new'
    | '/admin/events/'
    | '/admin/events/$eventId/checklist'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/join/$eventId'
    | '/admin/events/$eventId'
    | '/admin/events/new'
    | '/admin/events'
    | '/admin/events/$eventId/checklist'
  id:
    | '__root__'
    | '/'
    | '/join/$eventId'
    | '/admin/events/$eventId'
    | '/admin/events/new'
    | '/admin/events/'
    | '/admin/events/$eventId/checklist'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  JoinEventIdRoute: typeof JoinEventIdRoute
  AdminEventsEventIdRoute: typeof AdminEventsEventIdRouteWithChildren
  AdminEventsNewRoute: typeof AdminEventsNewRoute
  AdminEventsIndexRoute: typeof AdminEventsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join/$eventId': {
      id: '/join/$eventId'
      path: '/join/$eventId'
      fullPath: '/join/$eventId'
      preLoaderRoute: typeof JoinEventIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/events/': {
      id: '/admin/events/'
      path: '/admin/events'
      fullPath: '/admin/events/'
      preLoaderRoute: typeof AdminEventsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/events/new': {
      id: '/admin/events/new'
      path: '/admin/events/new'
      fullPath: '/admin/events/new'
      preLoaderRoute: typeof AdminEventsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/events/$eventId': {
      id: '/admin/events/$eventId'
      path: '/admin/events/$eventId'
      fullPath: '/admin/events/$eventId'
      preLoaderRoute: typeof AdminEventsEventIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/events/$eventId/checklist': {
      id: '/admin/events/$eventId/checklist'
      path: '/checklist'
      fullPath: '/admin/events/$eventId/checklist'
      preLoaderRoute: typeof AdminEventsEventIdChecklistRouteImport
      parentRoute: typeof AdminEventsEventIdRoute
    }
  }
}

interface AdminEventsEventIdRouteChildren {
  AdminEventsEventIdChecklistRoute: typeof AdminEventsEventIdChecklistRoute
}

const AdminEventsEventIdRouteChildren: AdminEventsEventIdRouteChildren = {
  AdminEventsEventIdChecklistRoute: AdminEventsEventIdChecklistRoute,
}

const AdminEventsEventIdRouteWithChildren =
  AdminEventsEventIdRoute._addFileChildren(AdminEventsEventIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  JoinEventIdRoute: JoinEventIdRoute,
  AdminEventsEventIdRoute: AdminEventsEventIdRouteWithChildren,
  AdminEventsNewRoute: AdminEventsNewRoute,
  AdminEventsIndexRoute: AdminEventsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
